---
name: Lint
on:
  push:
    paths:
      - geokde/**
      - .github/**
      - tests/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set-up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
