---
name: Test
on:
  push:
    paths:
      - geokde/**
      - .github/**
      - tests/**
jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os:
          - Ubuntu
          - macOS
          - Windows
        python-version:
          - '3.10'
        include:
          - os: Ubuntu
            image: ubuntu-latest
          - os: Windows
            image: windows-latest
          - os: macOS
            image: macos-latest
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set-up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: curl -sL https://install.python-poetry.org | python - -y

      - name: Update PATH for Ubuntu and MacOS
        if: ${{ matrix.os != 'Windows' }}
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Update Path for Windows
        if: ${{ matrix.os == 'Windows' }}
        run: echo "$APPDATA\Python\Scripts" >> $GITHUB_PATH

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Check Poetry lock
        run: poetry check --lock

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest -s
